inherit_from: .rubocop_todo.yml

Style/HashSyntax:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
